health_issues = [
    "Common Cold",
    "Flu (Influenza)",
    "Acute Respiratory Infections",
    "Injuries",
    "Back Pain",
    "Skin Disorders",
    "High Blood Pressure",
    "Diabetes",
    "Headaches",
    "Allergies",
    "Gastrointestinal Issues",
    "Anxiety and Depression",
    "Joint Pain",
    "Ear Infections",
    "Vision Problems",
    "Thyroid Disorders",
    "Urinary Tract Infections (UTIs)",
    "Sexual Health",
    "Routine Check-ups and Preventive Care",
    "Weight Management",
    "Cancer Screenings",
    "Respiratory Allergies",
    "Heart Conditions",
    "Chronic Pain Management",
    "Sleep Disorders",
    "Nutritional Guidance",
]
